### ISSUE TITLE
Possible issue with escape sequences in string value?

### ISSUE THREAD

**Issue by PaulTice** [StringEpsilon/fbJson#7]
When there is more than one escaped quote inside a string, the second escaped quote doesn't get skipped (escaped) correctly. 
Instead, it seems to be parsed as the end quote.
I'm guessing that since the next non-whitespace character isn't a comma or a curly brace, parsing fails.

HTML descriptions require style tags to be within a pair of quotes, this is how this came to my attention.

This key:value pair fails to parse, and ends parsing of any further pairs:
`"description":"<p><span style=\"font-family: 'arial black', 'avant garde';\">4 Pin Test setting, with comma<\/span><\/p>"`

This passes ok:
`"description":"<p>4 Pin Test setting with comma, semicolon ; single quote ' and colon :<\/p>"`

This, with two escaped quotes, doesn't pass:
`"4PinTest","description":"<p>4 Pin Test setting with comma, semicolon ; single quote ' and colon : and&nbsp; quote \" and quote \"<\/p>"`

But this, with one escaped quote, does: 
`"description":"<p>4 Pin Test setting with comma, semicolon ; single quote ' and colon : and&nbsp; quote \"<\/p>"`

jsonitem.datatype returns -1 on fail. 
jsonitem.count =5, which is the number of pairs before the failing pair, and the data is correct for those pairs.

**Comment by StringEpsilon** [comment]
Sorry for the late response. I took a break from FreeBASIC stuff.

The issue was in the DeEscapeString() function, line 48 needs to be a "continue for". I'll publish a new version shortly.
