### ISSUE TITLE
Another fbJSON

### ISSUE THREAD

**Issue by mrozbarry** [StringEpsilon/fbJson#9]
Hi StringEpsilon,

I actually came across this project completely randomly, and thought, "Hey, I wrote a JSON parser for FreeBASIC years ago," [fbjson](https://github.com/mrozbarry/fbjson).

I haven't written FreeBASIC in a couple of years now, but if there's anything you want to salvage from my old library, feel free, as long as you link back to my repo (which I might archive).

Anyway, this looks cool, good job!

**Comment by StringEpsilon** [comment]
I appreciate the sentiment. Thank you :)
